// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpbb0TBCiMOB3hyh6u2h_ouUQCxXLZOA',
    appId: '1:854439097514:web:cc13310eb8983f49630cd3',
    messagingSenderId: '854439097514',
    projectId: 'chat-app-8cf8c',
    authDomain: 'chat-app-8cf8c.firebaseapp.com',
    storageBucket: 'chat-app-8cf8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdRBihOo0uQGUZ65KlyWHwwe0ZRCJOhs',
    appId: '1:854439097514:android:42389b8dfe1f87e6630cd3',
    messagingSenderId: '854439097514',
    projectId: 'chat-app-8cf8c',
    storageBucket: 'chat-app-8cf8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIPMJ5ZZ4mC4lb-MJwrKdzuTMCtNRTy8g',
    appId: '1:854439097514:ios:a1604f670ee146c0630cd3',
    messagingSenderId: '854439097514',
    projectId: 'chat-app-8cf8c',
    storageBucket: 'chat-app-8cf8c.firebasestorage.app',
    iosBundleId: 'com.example.chatAppTeamMentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIPMJ5ZZ4mC4lb-MJwrKdzuTMCtNRTy8g',
    appId: '1:854439097514:ios:a1604f670ee146c0630cd3',
    messagingSenderId: '854439097514',
    projectId: 'chat-app-8cf8c',
    storageBucket: 'chat-app-8cf8c.firebasestorage.app',
    iosBundleId: 'com.example.chatAppTeamMentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPpbb0TBCiMOB3hyh6u2h_ouUQCxXLZOA',
    appId: '1:854439097514:web:c0d688811430d446630cd3',
    messagingSenderId: '854439097514',
    projectId: 'chat-app-8cf8c',
    authDomain: 'chat-app-8cf8c.firebaseapp.com',
    storageBucket: 'chat-app-8cf8c.firebasestorage.app',
  );
}
